spring:
  application:
    name: loababa

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_SECRET}
    response-type: ${OAUTH_KAKAO_RESPONSE_TYPE}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time-in-sec: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME_IN_SEC}
  refresh-token-expiration-time-in-sec: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME_IN_SEC}
  lossam-sign-up-key-expiration-time-in-sec: ${JWT_LOSSAM_SIGN_UP_KEY_EXPIRATION_TIME_IN_SEC}

discord:
  lossam-signup-webhook-url: ${DISCORD_LOSSAM_SIGNUP_WEBHOOK_URL}
  error-notification-webhook-url: ${DISCORD_ERROR_NOTIFICATION_WEBHOOK_URL}
  consulting-notification-webhook-url: ${DISCORD_CONSULTING_NOTIFICATION_WEBHOOK_URL}

url:
  lossam-sign-up: ${URL_LOSSAM_SIGN_UP}

aws:
  iam:
    access-key: ${AWS_IAM_ACCESS_KEY}
    secret-key: ${AWS_IAM_SECRET_KEY}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN_NAME}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    public-bucket-prefix: ${AWS_PUBLIC_BUCKET_PREFIX}

domain:
  front: ${DOMAIN_FRONT}
  back: ${DOMAIN_BACK}


